### ISSUE TITLE
SAFE Network instead of Safe Network

### ISSUE THREAD

**Issue by frabrunelle** [safe-network-explained/safe-network-explained.github.io#1]
Hey Ian,

I've been thinking it could be a good idea to write "SAFE Network" instead of "Safe Network" or "safe network", just to be more consistent because that's usually how it's written. Let me know what you think, I could send a pull request if you'd like 🙂

**Comment by iancoleman** [comment]
Good idea. I can't get to this before late this week, so if you submit a PR before then I'll accept it otherwise I'll try to get to it later in the week.
